Diesen Programm stellt ein FEM einen graden Stabes dar, der entlag seiner Ausdehnung belastet wird.
Der Stab hat dabei überall den gleichen Querschnitt und das gleiche E-Modul.

Für die Verarbeitung der Matrizien nutze ich numpy. Numpy ist eine Python Bibliothek die zum großen Teil in C geschrieben ist und somit die Rechnenleistung effiziernter nutzt. 
Bitte den Block zur installertion des Paketes nur ausführen, wenn noch keine Installation vorliegt. 

In [53]:
# pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [54]:
import numpy as np

Im Folgenden definiere ich die Parameter für die Aufgabenstellung. 

L    < >  Länge des Stabes.

A    < >  Querschnittsfläche des Stabes.

E    < >  Elastitizitätsmodul.

n_e  < >  Anzahl des Elemente des Stabes. 

In [55]:
L = 1.0       
A = 2.0       
E = 200.0     
n_e = 4

Zwei weitere Parameter ergeben sich direkt aus den gegebenen Größen.

n_k < > Anzahl der Knoten

k_cors < > Koordinaten der Knoten


In [56]:
n_k = n_e + 1
k_cors = np.linspace(0, L, n_k)

Nun stellen wir die Steifigkeitsmatrix auf.  
$$ 
K  = \frac{A \cdot E}{ \frac{L}{n_e}} \begin{bmatrix}
1 & -1 \\
-1 & 1
\end{bmatrix}

$$

In [57]:
k_local = (A*E/(L/n_e)) * np.array([[1, -1], [-1, 1]])

Die globale Steifigkeitsmatrix setzt sich aus den Steifigekeitsmatrizen der Knoten zusammen. 
Der ausdruck i:i+2 und i:i+2 ist daafür verantwortlich, dass sich die jeweiligen Matrizen auf einer Diagonalen in der allgeimnen Matrix wiederfinden. 

In [58]:
K = np.zeros((n_k, n_k))
for i in range(n_e):
    K[i:i+2, i:i+2] += k_local

Nun gestalte ich einen Lastvektor.np.zero gibt dabei einen Voktor voller Nullen zurück. 


In [59]:
F = np.zeros(n_k)
F[-1] = 10.0

Nun legen wir die Anfangsbedingungen fest. 

In [60]:
K[0,:] = 0  # Erste Zeile wird gleich null gesetzt
K[:,0] = 0  # Erste Spalte wird gleich null gesetzt
K[0,0] = 1  # Erstes Element wird gleich eins gesetzt, somit bleibt matrix invertiertbar
F[0] = 0    # Keine Kraft wirkt am ersten Knoten

Bevor ich das Gleichungssystem löse, lasse ich die Matrix und den Vektor ausgeben.

In [61]:
print("Globale Steifigkeitsmatrix K:")
print(K)
print("\nLastvektor F:")
print(F)

Globale Steifigkeitsmatrix K:
[[ 1.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00]
 [ 0.0e+00  3.2e+03 -1.6e+03  0.0e+00  0.0e+00]
 [ 0.0e+00 -1.6e+03  3.2e+03 -1.6e+03  0.0e+00]
 [ 0.0e+00  0.0e+00 -1.6e+03  3.2e+03 -1.6e+03]
 [ 0.0e+00  0.0e+00  0.0e+00 -1.6e+03  1.6e+03]]

Lastvektor F:
[ 0.  0.  0.  0. 10.]


Nun Lösen wir das Gleichungssystem und geben die Lösung aus.    

In [62]:
dis  = np.linalg.solve(K, F)
print(dis)

[0.      0.00625 0.0125  0.01875 0.025  ]
